version: '3.2'
services:
  app:
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "3000:3000"  
    depends_on:
      - sql
      - nosql
    environment:
      DATABASE_URL: postgres://trustmebank_user_dev@postgres/trustmebank_db_dev?authSource=admin
    command: ["./wait-for-it.sh", "nosql:27017", "--", "npm", "run", "start:docker"]
  sql:
    image: postgres:9.6.2
    restart: always
    environment:
      POSTGRES_USER: trustmebank_sql_dev
      POSTGRES_PASSWORD: trustmebank_sql_dev
      POSTGRES_DB: trustmebank_sql_dev
    ports:
      - 5432:5432
  nosql:
    image: mongo:3.6
    restart: always
    volumes:
    - ./mongodb/init-db.sh:/docker-entrypoint-initdb.d/01-init-db.sh
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
      MONGO_USERNAME: ${MONGODB_USER}
      MONGO_PASSWORD: ${MONGODB_PASSWORD}
    ports:
        - "27017:27017"
  fe:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
    command: ["./wait-for-it.sh", "app:3000", "--", "nginx", "-g", "daemon off;"]

  proxy:
    image: datadog/squid
    ports:
      - "3128:3128"
